### ISSUE TITLE
Tutorial section: useful prior knowledge

### ISSUE THREAD

**Issue by ramirezfranciscof** [aiidateam/aiida-tutorials#329] opened 2021-05-31 11:01 UTC
Comment from the previous tutorial:

> Add links to some basic Python tutorials they can follow before the tutorial. I suppose they could also just google this… But we might as well.

I personally think linking to a basic tutorial would be contradictory with the fact that we require basic python knowledge.

Perhaps what we could do is link to more specific articles for advanced topics that would be useful to know and are not necessarily "basic" python (what is a decorator, using python path, nested copying, class inheritance). We should do this in a way that makes it clear that we don't maintain these external resources so the owners can decide to take them down or whatever, maybe by just mentioning the topics and linking to "example explanations".

**Comment by mbercx** [comment] 2021-06-09 11:05
Duplicate of https://github.com/aiidateam/aiida-tutorials/issues/348 😅

**Closed as completed by mbercx** 2021-06-09 11:05 UTC
